# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Введите текст вопроса', max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='tf_question',
            name='correct',
            field=models.BooleanField(default=False, help_text='Отметьте здесь, если утверждение верно.', verbose_name='Правильно'),
        ),
    ]
